### ISSUE TITLE
why no ddos men

### ISSUE THREAD

**Issue by SSources** [NiceAesth/2pacalypse#4]
i try ddos men it not work do what i do ?
![téléchargement (3)](https://user-images.githubusercontent.com/69769581/213469634-408b1012-1ff3-4ab2-b8ef-41639c8ce75c.jpg)

**Comment by NiceAesth** [comment]
![image](https://user-images.githubusercontent.com/8437201/213475077-d96273e9-e57c-498f-b707-3a64d590682a.png)
